<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-28 22:29
=======
# Generated by Django 3.2.8 on 2021-11-03 21:16
>>>>>>> daaf71756bf99639c0cfa4380cfb82bdebcbeb1e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_services_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Like',
        ),
    ]
