# Generated by Django 3.2.7 on 2021-10-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_services_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Like',
        ),
    ]
