# Generated by Django 3.2.7 on 2021-11-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_auto_20211130_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='name',
        ),
    ]
