# Generated by Django 3.2.7 on 2021-12-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_services_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='people',
            field=models.IntegerField(choices=[(30, 30), (60, 60), (90, 90)], default=1),
        ),
    ]
