# Generated by Django 3.2.8 on 2021-10-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=40)),
                ('service', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=40)),
                ('t_service', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
