# Generated by Django 3.2.8 on 2021-11-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('membership', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservations.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='t_service',
        ),
        migrations.AddField(
            model_name='reservations',
            name='ID',
            field=models.CharField(default='+', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reservations',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='room',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='service',
            field=models.CharField(choices=[('MB', 'mineral baths'), ('MA', 'massages'), ('FA', 'facials'), ('ST', 'specialty treatments')], default='MB', max_length=4),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='timing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Reservations.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservations.order')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservations.reservations')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.cart')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservations.reservations')),
            ],
        ),
    ]
