# Generated by Django 3.2.8 on 2021-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_auto_20211106_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='00000', max_length=255),
        ),
    ]
