# Generated by Django 3.2.8 on 2021-11-12 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_address_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='ID',
        ),
        migrations.AddField(
            model_name='reservations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
