# Generated by Django 3.2.8 on 2021-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0004_auto_20211111_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='reservations',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='service',
            field=models.CharField(choices=[('SW', 'Swedish'), ('SH', 'Shiatsu'), ('DT', 'Deep Tissue'), ('ST', 'Normal'), ('CO', 'Collagen'), ('HS', 'Hot Stone'), ('SU', 'Sugar'), ('SC', 'Scrub'), ('HB', 'Herbal Body Wrap'), ('BM', 'Bontanical Mud Wrap')], default='ST', max_length=4),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
