# Generated by Django 3.2.8 on 2021-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0005_auto_20211130_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='room',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='timing',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='service',
            field=models.CharField(choices=[('SW', 'Swedish'), ('SH', 'Shiatsu'), ('DT', 'Deep Tissue'), ('NO', 'Normal'), ('CO', 'Collagen'), ('HS', 'Hot Stone'), ('SU', 'Sugar'), ('SC', 'Scrub'), ('HB', 'Herbal Body Wrap'), ('BM', 'Bontanical Mud Wrap')], default='NO', max_length=4),
        ),
    ]
